//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.18 at 03:29:57 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soap.test.com.br/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.test.soap.model;
